### ISSUE TITLE
Vue migration: sorting settings is not being saved and also have incorrect default value

### ISSUE THREAD

**Issue by itbeard** [awclub/catalog#12]
Steps to reproduce:
- Open catalog
- Change sorting to "Date"
- Update page
- Catalog has sorting by "Name" (default value)

Expected behavior:
- After reloading services should be sorted by date
- Default sorting direction should be "Date DESC" (now it is "Name ASC)

**Comment by gamezovladislav** [comment]
https://github.com/awclub/catalog/commit/59a8355aa285088fc3514f0d6cdf52d7618b10c5

**Comment by gamezovladislav** [comment]
set default order
https://github.com/awclub/catalog/commit/cdc85696f2675c6cc527aad9e26c4e7ffee2aea3
