### ISSUE TITLE
Vue migration: "Copied to clipboard" wrong behavior

### ISSUE THREAD

**Issue by itbeard** [awclub/catalog#13]
Step to reproduce:
- Open catalog
- Press the "Copy link to service" button
- The "Copied to clipboard" tooltip does not hide automatically

<img width="433" alt="image" src="https://github.com/awclub/catalog/assets/45439635/99d54273-5f36-445e-920e-e2f20610c0c9">

Expected behavior:
- Tooltip should hide automatically after 3 sec

**Comment by gamezovladislav** [comment]
https://github.com/awclub/catalog/commit/406f5e2073a08eb70a36f48dc413977b5ac2c026
