### ISSUE TITLE
Add new servisec from episode 31

### ISSUE THREAD

**Issue by itbeard** [awclub/catalog#36]
New services from podcast episode №31 should be added to catalog.

List of services to add:
- StabilityAudio 2.0
   - https://stableaudio.com
   - Stable Audio 2.0, developed by Stability AI, represents a significant advancement in AI-generated audio technology. This model is capable of producing high-quality, full tracks with coherent musical structures up to three minutes in length at 44.1kHz stereo. It introduces several new features and improvements over its predecessor, Stable Audio 1.0.
- devika
   - https://github.com/stitionai/devika
   - Devika is an Agentic AI Software Engineer that can understand high-level human instructions, break them down into steps, research relevant information, and write code to achieve the given objective. Devika aims to be a competitive open-source alternative to Devin by Cognition AI. 
- SWE-agent 
   - https://github.com/princeton-nlp/SWE-agent
   - SWE-agent takes a GitHub issue and tries to automatically fix it, using GPT-4, or your LM of choice. It solves 12.47% of bugs in the SWE-bench evaluation set and takes just 1 minute to run.
- CodeRabbit
   - https://coderabbit.ai
   - CodeRabbit is an AI-driven platform designed to revolutionize the code review process. It offers automated, line-by-line feedback on code changes, suggesting improvements and corrections to enhance code efficiency and robustness. The platform significantly reduces the time and effort required for manual code reviews by providing insightful feedback and enabling contextual conversations within GitHub's comment threads
- Command R+
   - https://txt.cohere.com/command-r-plus-microsoft-azure
- VoiceCraft
   - https://github.com/jasonppy/VoiceCraft
   - Zero-Shot Speech Editing and Text-to-Speech in the Wild 

Check that services are not already presented in the catalog.
Check that added services have Russian and English translations.

Link to the podcast episode:  https://www.youtube.com/watch?v=0GXy99OPMTU

**Comment by itbeard** [comment]
The date of episode release is 6 April 2024

**Comment by xxxAleksandrxxx** [comment]
Please check pull request https://github.com/awclub/catalog/pull/40
