### ISSUE TITLE
тэг search дублирует название phind

### ISSUE THREAD

**Issue by asulinov** [awclub/catalog#9]
**[Name and URL of the tool](https://awclub.github.io/catalog/)**
**you.com под видом phind**
ставишь тэг search - выдает you.com под видом phind (правый верхний на скрине), при этом phind тоже есть с отдельным описанием (левый нижний). 
<img width="1239" alt="Screenshot 2024-01-16 at 19 05 41" src="https://github.com/awclub/catalog/assets/79568745/45ed0360-6bdb-47d9-9d8c-ad1f56942da7">

**Comment by itbeard** [comment]
fixed, thx!
